### ISSUE TITLE
UI fixes for Login 

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/mobile#23]
1) On the login screen can there be a small space between the logo and the form? When you enter the email ID field the text is getting hidden behind the logo
2) Maybe all lines in form can be grey-gravel and brand-orange on hover/on click. Seems like a too much red on the screen right now.
3) Can the text in the sign up form be left aligned?
4) Over all can the font size by 2 pts smaller on the sign up form. It seems too crowded.
5) E-mail should be spelt consistently all over.
6) Also Title case can be consistent all over, sign up and login forms.
7) Size of the register button can be wider and use same bold font as login

**Comment by subhaklp** [comment]
@meghaklp , noted. Will work on it today.

**Comment by subhaklp** [comment]
#2 is turning out to be complicated. Shelving it for later.

**Comment by subhaklp** [comment]
Everything else is fixed with latest commit to master.

**Comment by meghaklp** [comment]
This is done.
