### ISSUE TITLE
List only one survey for now, on the app

### ISSUE THREAD

**Issue by deviprasadadiga** [klpdotorg/mobile#24]
Need to change the number of surveys listed on the app. Currently it is limited to just one survey- Community Infrastructure by Akshara Foundation.

**Comment by iambibhas** [comment]
So remove all the other surveys and keep just the Community survey? Because source = mobile?

**Comment by harisibrahimkv** [comment]
@iambibhas Yep. Just "Community" with one active questiongroup. We only need Surveys, questiongroups and questions associated with source `mobile` to be on the app. This is done.
