### ISSUE TITLE
Populate the db with Boundary + School data and bundle it along with the app.

### ISSUE THREAD

**Issue by harisibrahimkv** [klpdotorg/mobile#27]

**Comment by iambibhas** [comment]
Implemented this. This is happening now. 
- We need to finalize the surveys we're going to ship with the db. There were 4 before. Now after the addition of surveys with mobile source, now there are 5.

**Comment by iambibhas** [comment]
Same as #22.

**Comment by harisibrahimkv** [comment]
There should only be one. It should be "Community" with associated questiongroups having source as `mobile` with only 1 active questiongroup among them.

**Comment by harisibrahimkv** [comment]
Boundary and school info is bundled along with the app now.
