### ISSUE TITLE
Get data from server and sync.

### ISSUE THREAD

**Issue by harisibrahimkv** [klpdotorg/mobile#29]
Right now getting the data from the server, just, well, gets the data from the server. Implement a sync mechanism where it ensures the data is in "sync" by updating deleted and changed records.

**Comment by iambibhas** [comment]
@harisibrahimkv now that we have prepopulated database, do we need the school sync option anymore? If we remove that I can implement rest of the sync to update or delete.

**Comment by harisibrahimkv** [comment]
We just need to roll all the API endpoints to fetch data from production before finalizing on the records being stored in localStorage. But if we have prepopulated database, we can make both Boundary and School sync optional (considering if someday someone updates a school or boundary record).

**Comment by harisibrahimkv** [comment]
This has been implemented by converting all db operation to use the squidb `insertwithId`. It creates a new record if the id is not present. It updates a record if the id is present.
